server:
  port: 8085
#
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/productorder
    username: postgres
    password: mylove4u
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  main:
    web-application-type: servlet

  # eureka client config
  eureka:
    client:
      serviceUrl:
        defaultZone: localhost:8761/eureka/