spring:
  application:
    name: notification-server
    #eureka configuration
  eureka:
    client:
      serviceUri:
        defaultZone: localhost:8761/eureka/
        #kafka configuration
#  kafka:
#    bootstrap-servers: kafka://localhost:29092
#    consumer:
#      group-id: notificationId
#      properties:
#        spring:
#          json:
#            type:
#              mapping: event:com/ekene/MassageBuilderProperties

server:
    port: 8082